defaults:
  - wmx_data_collection@_here_
  - _self_

name: wmx_paep_real_wiping_board_image_dp_absolute_24fps

# 你的数据是 (H, W, 3) = (240, 320, 3)
image_shape: [3, 240, 320]

# 按你的实际数据路径改
dataset_path: /home/wmx/Reactive-Diffusion-Policy-on-Flexiv-rizon4s/dataset/wiping_board_stream_downsample1_zarr

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    # 腕部相机
    left_wrist_img:
      shape: ${task.image_shape}
      type: rgb

    # 外部相机
    external_img:
      shape: ${task.image_shape}
      type: rgb

    # 末端位姿（9维）
    left_robot_tcp_pose:
      shape: [9]
      type: low_dim

    # 夹爪开合宽度（1维）
    left_robot_gripper_width:
      shape: [1]
      type: low_dim
    
    #DP+末端六维力
    left_robot_tcp_wrench:
      shape: [6]
      type: low_dim

  # 动作：和你 zarr 里的 action 对应，10 维
  action:
    shape: [10]


env_runner:
  _target_: reactive_diffusion_policy.env_runner.ours_real_runner_w_fast.RealRunner
  eval_episodes: 10
  max_duration_time: 300

  # action_smoothing_alpha: 0.5
  # smooth_xyz_only: true

  tcp_action_update_interval: 6
  #gripper_action_update_interval: 6
  gripper_action_update_interval: 6
  # tcp_action_update_interval: 2
  # gripper_action_update_interval: 2
  tcp_pos_clip_range:
    - [-100, -100, 0.04]
    - [100, 100, 1.0]
  tcp_rot_clip_range:
    - [-100, -100, -100]
    - [100, 100, 100]
  latency_step: 2
  gripper_latency_step: 4
  # control_fps: 12        # DP 控制频率
  control_fps: 24        # 修改
  #inference_fps: 6
  inference_fps: 8 #每 3 个 control step 推理一次
  n_obs_steps: ${n_obs_steps}
  obs_temporal_downsample_ratio: 1
  task_name: ${task_name}
  transform_params: ${task.transforms}
  shape_meta: *shape_meta
  tcp_ensemble_buffer_params:
    ensemble_mode: 'new'
  gripper_ensemble_buffer_params:
    ensemble_mode: 'new'
  use_relative_action: ${task.dataset.relative_action}
  action_interpolation_ratio: 1
  enable_video_recording: False
  vcamera_server_ip:
    - 192.168.2.252
    - 192.168.2.252
  vcamera_server_port:
    - 8102
    - 8112
  env_params:
    robot_server_ip: ${task.robot_server.host_ip}
    robot_server_port: ${task.robot_server.port}
    device_mapping_server_ip: ${task.device_mapping_server.host_ip}
    device_mapping_server_port: ${task.device_mapping_server.port}
    data_processing_params:
      # TODO: fix this (support left or right)
      mode: 'single_arm_two_realsense_two_tactile'
      pca_param_dict:
        GelSight:
          n_components: 15
          normalize: False
          mode: 'Eval'
          store: False
          transformation_matrix_path: 'data/PCA_Transform_GelSight/pca_transform_matrix.npy'
          mean_matrix_path: 'data/PCA_Transform_GelSight/pca_mean_matrix.npy'
        McTac_v1:
          n_components: 15
          normalize: False
          mode: 'Eval'
          store: False
          transformation_matrix_path: 'data/PCA_Transform_McTAC_v1/pca_transform_matrix.npy'
          mean_matrix_path: 'data/PCA_Transform_McTAC_v1/pca_mean_matrix.npy'
      #max_fps: 10
      debug: False
    # gripper control params
    use_force_control_for_gripper: ${task.teleop_server.use_force_control_for_gripper}
    max_gripper_width: ${task.teleop_server.max_gripper_width}
    min_gripper_width: ${task.teleop_server.min_gripper_width}
    grasp_force: ${task.teleop_server.grasp_force}
    gripper_control_time_interval: ${task.teleop_server.gripper_control_time_interval}
    gripper_control_width_precision: ${task.teleop_server.gripper_control_width_precision}
    gripper_width_threshold: 0.046
    enable_gripper_width_clipping: False

  # #Fast policy params
  enable_fast: False
  fast_ckpt_path: /home/wmx/Reactive-Diffusion-Policy-on-Flexiv-rizon4s/Fast/train_fast_wiping_v2_run1/ckpt_best.pt
  fast_meta_path: /home/wmx/Reactive-Diffusion-Policy-on-Flexiv-rizon4s/Fast/train_fast_wiping_v2_run1/train_meta.json
  fast_device: cuda
  fast_hist_len: 8
  fast_wrench_clip_norm: 6.0
  fast_max_delta_xyz: 0.01
  fast_apply_rot: false
  fast_gate_mode: soft
  fast_gate_thr: 0.5
  fast_gate_use_contact: true
  fast_active_phase_ids: [1]      # wiping: progress=1
  fast_debug_log_every: 50

dataset:
  _target_: reactive_diffusion_policy.dataset.real_image_tactile_dataset.RealImageTactileDataset
  shape_meta: *shape_meta
  dataset_path: ${task.dataset_path}

  # ---- dynamic wrench history (for PAEP + fusion) ----
  add_wrench_hist: true
  force_hist: 48
  wrench_key: left_robot_tcp_wrench
  wrench_hist_key: wrench_hist
  wrench_hist_pad_mode: repeat_first

  # make dataset sampling consistent with 24Hz (no downsample)
  obs_temporal_downsample_ratio: 1


  horizon: ${horizon}
  pad_before: ${eval:'${dataset_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}

  n_obs_steps: ${dataset_obs_steps}
  n_latency_steps: ${n_latency_steps}

  seed: 42
  val_ratio: 0.0
  max_train_episodes: null

  # DP 这份是 absolute policy
  delta_action: false
  relative_action: false